"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";

const fetchBanners = async () => { const { data } = await axios.get("/api/banners/public", { timeout: 10000 }); if (!data?.success) throw new Error("Banner request failed"); return data.banners || []; };
export default function DynamicBannerCarousel({ fallback: Fallback }) {
  const router = useRouter(), rail = useRef(null), [active, setActive] = useState(0);
  const { data: banners, isLoading } = useQuery({ queryKey:["public-banners"], queryFn:fetchBanners, staleTime:300000, retry:false });
  useEffect(() => { if (!banners || banners.length < 2 || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const timer = window.setInterval(() => { const el = rail.current; if (!el) return; const next = (active + 1) % banners.length; el.scrollTo({ left: next * el.clientWidth, behavior: "smooth" }); setActive(next); }, 5000); return () => clearInterval(timer); }, [banners, active]);
  if (isLoading) return <div className="h-36 animate-pulse rounded-[22px] bg-slate-200 dark:bg-slate-800" />;
  if (!banners?.length) return <Fallback />;
  const scrollTo = (index) => { rail.current?.scrollTo({ left:index * rail.current.clientWidth, behavior:"smooth" }); setActive(index); };
  return <section className="overflow-hidden"><div ref={rail} onScroll={(e)=>setActive(Math.round(e.currentTarget.scrollLeft / Math.max(1,e.currentTarget.clientWidth)))} className="no-scrollbar flex snap-x snap-mandatory overflow-x-auto" aria-label="Featured promotions">{banners.map((b) => { const hasImage=!!b.imageUrl, imageOnly=b.contentStyle === "image"; const background=b.backgroundGradient ? `linear-gradient(${b.backgroundGradient.direction || "to right"}, ${b.backgroundGradient.from}, ${b.backgroundGradient.to})` : b.backgroundColor || "#ef5b0c"; return <button key={b._id} type="button" onClick={()=>b.ctaLink && router.push(b.ctaLink)} className="relative h-36 min-w-full snap-center overflow-hidden rounded-[22px] p-4 text-left text-white shadow-[0_10px_24px_rgba(15,23,42,.16)] sm:h-40 sm:p-5" style={{ background }} aria-label={b.ctaText ? `${b.title}: ${b.ctaText}` : b.title}>{hasImage && <img src={b.mobileImageUrl || b.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover" />}{hasImage && <div className={`absolute inset-0 ${imageOnly ? "bg-gradient-to-r from-black/75 via-black/35 to-black/10" : "bg-black/25"}`} />}<div className="relative z-10 flex h-full max-w-[78%] flex-col justify-center"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/85">{b.bannerType}</p><h2 className="mt-1 line-clamp-2 text-lg font-black leading-[1.05] sm:text-xl">{b.title}</h2>{(b.description || b.subtitle) && <p className="mt-1 line-clamp-2 text-xs font-medium leading-snug text-white/90">{b.description || b.subtitle}</p>}{b.ctaText && <span className="mt-2 inline-flex w-fit rounded-full bg-white px-3 py-1.5 text-[10px] font-black text-slate-900 shadow-sm">{b.ctaText}</span>}</div></button>; })}</div>{banners.length > 1 && <div className="mt-2 flex justify-center gap-1.5">{banners.map((b,index)=><button key={b._id} onClick={()=>scrollTo(index)} aria-label={`Show banner ${index + 1}`} className={`h-1.5 rounded-full transition-all ${active===index ? "w-5 bg-orange-500" : "w-1.5 bg-slate-300 dark:bg-slate-700"}`} />)}</div>}</section>;
}