export default function robots() {
  const baseUrl = 'https://www.melachow.com'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/home',
          '/all-restaurants',
          '/all-foods',
          '/restaurants/',
          '/food-details/',
          '/combo-details/',
          '/auth/signin',
          '/auth/rider/login',
          '/vendors/auth/login',
          '/vendors/auth/register',
          '/search',
          '/faqs',
          '/trending-foods',
          '/trending-restaurants',
        ],
        disallow: [
          '/auth/',
          '/vendors/auth/',
          '/rider/auth/',
          '/admin/',
          '/vendors/dashboard',
          '/vendors/create-food',
          '/vendors/my-foods',
          '/vendors/my-combos',
          '/vendors/menu',
          '/vendors/products',
          '/vendors/profile',
          '/vendors/order',
          '/vendors/transactions',
          '/vendors/coupons',
          '/vendors/notifications',
          '/vendors/riders',
          '/vendors/reviews',
          '/vendors/pending-approval',
          '/rider/',
          '/checkout',
          '/cart',
          '/orders',
          '/track-orders',
          '/verify-payment',
          '/profile',
          '/notifications',
          '/support',
          '/get-help',
          '/api/',
          '/v1/',
          '/offline',
        ],
      },
      { userAgent: 'GPTBot', disallow: ['/'] },
      { userAgent: 'CCBot', disallow: ['/'] },
      { userAgent: 'Google-Extended', disallow: ['/'] },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
